# Generated by Django 6.1 on 2026-10-05 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingeniero',
            fields=[
                ('rut', models.CharField(help_text='Ej: 12.345.678-9', max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('sueldo_base', models.DecimalField(decimal_places=2, help_text='Dato sensible', max_digits=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ingenieros/')),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_proyecto', models.CharField(max_length=100)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('documento_contrato', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('ingeniero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='obras_civiles.ingeniero')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='obras_civiles.proyecto')),
            ],
            options={
                'unique_together': {('ingeniero', 'proyecto')},
            },
        ),
    ]
