# Generated by Django 6.1 on 2026-10-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras_civiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/'),
        ),
    ]
