# Generated by Django 6.1 on 2026-10-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('institucion', models.CharField(max_length=150)),
                ('en_curso', models.BooleanField(default=False)),
                ('fecha_obtencion', models.DateField(blank=True, null=True)),
                ('credencial_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('icono_css', models.CharField(help_text='Ej: devicon-python-plain colored', max_length=100)),
                ('usos_contador', models.IntegerField(default=0, help_text='Se actualiza automáticamente por transacción')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='proyectos', to='arquitectura_ti.tecnologia')),
            ],
        ),
    ]
